# Generated by Django 6.0.5 on 2026-05-10 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_area_rename_text_habit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.area'),
        ),
        migrations.AddField(
            model_name='habit',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
