# Generated by Django 6.0.5 on 2026-05-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_area_habit_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='text',
            new_name='notes',
        ),
    ]
