# Generated by Django 6.0.5 on 2026-05-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_rename_text_habit_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
