# Generated by Django 6.0.5 on 2026-06-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_plan_tier_habitplan_habittier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='start_date',
        ),
        migrations.AddField(
            model_name='plan',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
