# Generated by Django 6.0.5 on 2026-06-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_remove_plan_start_date_plan_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
