# Generated by Django 6.0.5 on 2026-06-15 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_chain_habitchain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['habitplan__plan__start_time', 'habitchain__order']},
        ),
    ]
