# Generated by Django 6.0.5 on 2026-06-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0012_goal_alter_plan_options_habitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('UNTRACKED', 'Untracked')], default='UNTRACKED', max_length=20),
        ),
    ]
