# Generated by Django 6.0.5 on 2026-06-16 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0013_habitlog_notes_habitlog_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['habitplan__plan__start_time', 'habitplan__order']},
        ),
        migrations.RemoveField(
            model_name='habitlog',
            name='habit_plan',
        ),
        migrations.AddField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit'),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitplan',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.chain'),
        ),
        migrations.AddField(
            model_name='habitplan',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='HabitChain',
        ),
    ]
