# Generated by Django 6.0.5 on 2026-06-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0014_delete_goal_alter_habit_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HabitPlan',
            new_name='Schedule',
        ),
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['schedule__plan__start_time', 'schedule__order']},
        ),
    ]
