# Generated by Django 6.0.5 on 2026-06-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0015_rename_habitplan_schedule_alter_habit_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='one_log_per_habit_per_day'),
        ),
    ]
