# Generated by Django 6.0.5 on 2026-06-16 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0016_habitlog_one_log_per_habit_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.plan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'date'), name='one_time_override_per_plan_per_day')],
            },
        ),
    ]
