# Generated by Django 6.0.5 on 2026-06-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0017_planday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habits', models.ManyToManyField(related_name='day_notes', to='habits.habit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
