# Generated by Django 6.0.5 on 2026-06-20 20:09

from django.db import migrations


def copy_notes_forward(apps, schema_editor):
    """Turn each HabitLog's per-day notes text into a Note linked to that habit.

    We leave HabitLog.notes untouched (dropped later in its own migration), so
    the original text stays as a fallback until the new feature is proven.
    """
    HabitLog = apps.get_model("habits", "HabitLog")
    Note = apps.get_model("habits", "Note")

    logs = (
        HabitLog.objects
        .filter(habit__isnull=False)
        .exclude(notes__isnull=True)
        .exclude(notes__exact="")
    )
    for log in logs:
        note = Note.objects.create(body=log.notes, date=log.date)
        note.habits.add(log.habit)


def copy_notes_reverse(apps, schema_editor):
    """Undo: remove every Note. Safe because the source text still lives in
    HabitLog.notes (we never cleared it)."""
    Note = apps.get_model("habits", "Note")
    Note.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0018_note'),
    ]

    operations = [
        migrations.RunPython(copy_notes_forward, copy_notes_reverse),
    ]
