# Generated by Django 6.0.5 on 2026-06-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0019_copy_habitlog_notes_to_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
