# Generated by Django 6.0.5 on 2026-06-21 05:37

import django.db.models.deletion
from django.db import migrations, models


def seed_tiers(apps, schema_editor):
    """The Tier lookup is the fixed ladder Roots=1, Growth=2, Flourish=3. Seed
    the three rows so habit-tiers have something to point at. Idempotent."""
    Tier = apps.get_model("habits", "Tier")
    for level in (1, 2, 3):
        Tier.objects.get_or_create(level=level)


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0021_routine_schedule_routine'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('started', models.DateField()),
            ],
            options={
                'ordering': ['-started', '-id'],
            },
        ),
        migrations.AddField(
            model_name='habitlog',
            name='achieved_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.tier'),
        ),
        migrations.AddConstraint(
            model_name='habittier',
            constraint=models.UniqueConstraint(fields=('habit', 'tier'), name='one_habittier_per_habit_tier'),
        ),
        migrations.AddField(
            model_name='tiervalue',
            name='habit_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habittier'),
        ),
        # Seed the fixed Tier ladder (1/2/3). Reverse is a no-op so rolling back
        # never deletes a Tier that logs/habit-tiers still point at.
        migrations.RunPython(seed_tiers, migrations.RunPython.noop),
    ]
