# Generated by Django 6.0.5 on 2026-06-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0022_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
