# Generated by Django 6.0.5 on 2026-06-21 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0023_habit_is_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.tier'),
        ),
    ]
