# Generated by Django 6.0.5 on 2026-06-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0024_schedule_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
