# Generated by Django 6.0.5 on 2026-06-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0025_habit_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='is_important',
        ),
        migrations.AddField(
            model_name='habit',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
    ]
