# Generated by Django 6.0.5 on 2026-06-23 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0027_habitlog_per_version_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('habit_name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.chain')),
                ('habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.plan')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.routine')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.tier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('tier__isnull', False)), fields=('date', 'habit', 'tier'), name='one_scheduleday_per_date_habit_tier'), models.UniqueConstraint(condition=models.Q(('tier__isnull', True)), fields=('date', 'habit'), name='one_untiered_scheduleday_per_date_habit')],
            },
        ),
    ]
