# Generated by Django 6.0.5 on 2026-06-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0028_scheduleday'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
