# Generated by Django 6.0.5 on 2026-06-24 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0029_plan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='scheduleday',
            name='chain',
        ),
        migrations.DeleteModel(
            name='Chain',
        ),
    ]
