# Generated by Django 6.0.5 on 2026-06-24 02:30

import datetime
import django.db.models.deletion
from django.db import migrations, models

BASE_VALID_FROM = datetime.date(1970, 1, 1)


def backfill_valid_from(apps, schema_editor):
    """Stamp every pre-existing Schedule with the base sentinel: 'this has always
    been the plan.' Additive only — no placement moves. (AddField's default
    already covers this; this makes the base generation explicit and survives any
    pre-existing NULLs.)"""
    Schedule = apps.get_model('habits', 'Schedule')
    Schedule.objects.update(valid_from=BASE_VALID_FROM)


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op: the AddField rollback drops the column entirely, so
    there is nothing to undo here."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0030_remove_schedule_chain_remove_scheduleday_chain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='valid_from',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.RunPython(backfill_valid_from, noop_reverse),
        migrations.CreateModel(
            name='PlanTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('start_time', models.TimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.plan')),
            ],
        ),
    ]
