# Generated by Django 6.0.5 on 2026-06-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0031_schedule_valid_from_plantime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('motivation', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habits', models.ManyToManyField(blank=True, related_name='aspirations', to='habits.habit')),
            ],
        ),
    ]
