# Generated by Django 6.0.5 on 2026-06-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0033_rename_plan_to_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='ended_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
