# Generated by Django 6.0.5 on 2026-06-29 06:40

import django.db.models.deletion
from django.db import migrations, models


def open_windows_from_ended_on(apps, schema_editor):
    """Backfill: every habit currently paused (ended_on set) needs an OPEN pause
    window starting on that date, or the new window-based schedule filter would
    forget it's paused. Idempotent — only creates one if no open window exists."""
    Habit = apps.get_model('habits', 'Habit')
    HabitPause = apps.get_model('habits', 'HabitPause')
    for habit in Habit.objects.exclude(ended_on__isnull=True):
        exists = HabitPause.objects.filter(habit=habit, end_date__isnull=True).exists()
        if not exists:
            HabitPause.objects.create(habit=habit, start_date=habit.ended_on)


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0034_habit_ended_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='habits.habit')),
            ],
            options={
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.RunPython(open_windows_from_ended_on, migrations.RunPython.noop),
    ]
