# Generated by Django 6.0.5 on 2026-07-09 00:21
#
# P0 of the version-ladder migration (docs/contracts/versions.md, minimal slice):
# create the Version table AND copy every habit's existing Roots/Growth rungs into
# it. Purely additive — HabitTier / TierValue / HabitLog.tier are all left
# untouched as the cross-check; nothing reads Version yet. The copy is the whole
# point: a schema-only migration here would strand every ladder (the exact way
# migration 0014 silently wiped the chains).

from collections import defaultdict

import django.db.models.deletion
from django.db import migrations, models


def copy_tiers_to_versions(apps, schema_editor):
    """Every (habit, tier) that exists as a HabitTier OR is referenced by a log /
    placement -> a contiguous Version row (level 1..N, low tier first), value = the
    HabitTier's newest TierValue (blank if none), label = the tier.

    Why the UNION and not just HabitTier: a habit can have historical logs at a
    tier it no longer keeps a HabitTier for (e.g. "Outfit" was un-tiered but its
    old Roots/Growth completions remain). Copying only current HabitTiers would
    leave those logs unmappable, and P1's version-keyed uniqueness would then see
    two "no rung" logs on one day and refuse. Minting a rung for every tier the
    data actually uses keeps all history and makes P1 apply cleanly. Such a
    recovered rung has a blank value; she can delete it later (logs SET_NULL).

    Renumbering to 1..N (not the global tier level) keeps `level` meaning "position
    on THIS ladder"; the tag lives on `label`, so P1 maps old tier-keyed rows onto
    versions by label and a later relabel never disturbs history.
    """
    HabitTier = apps.get_model("habits", "HabitTier")
    TierValue = apps.get_model("habits", "TierValue")
    Tier = apps.get_model("habits", "Tier")
    HabitLog = apps.get_model("habits", "HabitLog")
    Schedule = apps.get_model("habits", "Schedule")
    ScheduleDay = apps.get_model("habits", "ScheduleDay")
    Version = apps.get_model("habits", "Version")

    tier_level = {t.id: t.level for t in Tier.objects.all()}

    # (habit_id, tier_id) -> newest TierValue text, for pairs that have a HabitTier
    value_of = {}
    for ht in HabitTier.objects.exclude(tier_id=None):
        tv = (
            TierValue.objects.filter(habit_tier=ht)
            .order_by("-started", "-id")
            .first()
        )
        value_of[(ht.habit_id, ht.tier_id)] = tv.value if tv else ""

    # the union: current tiers + every tier referenced by history
    pairs = set(value_of.keys())
    for M in (HabitLog, Schedule, ScheduleDay):
        for hid, tid in (
            M.objects.exclude(tier_id=None).exclude(habit_id=None)
            .values_list("habit_id", "tier_id").distinct()
        ):
            pairs.add((hid, tid))

    by_habit = defaultdict(set)
    for hid, tid in pairs:
        by_habit[hid].add(tid)

    rows = []
    for habit_id, tids in by_habit.items():
        for level, tid in enumerate(sorted(tids, key=lambda t: tier_level.get(t, 0)), start=1):
            rows.append(
                Version(
                    habit_id=habit_id,
                    level=level,
                    value=value_of.get((habit_id, tid), ""),
                    label_id=tid,
                )
            )
    Version.objects.bulk_create(rows)


def delete_versions(apps, schema_editor):
    apps.get_model("habits", "Version").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0035_habitpause'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=100)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='habits.habit')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.tier')),
            ],
            options={
                'ordering': ['habit_id', 'level'],
                'constraints': [models.UniqueConstraint(fields=('habit', 'level'), name='one_version_per_habit_level')],
            },
        ),
        migrations.RunPython(copy_tiers_to_versions, delete_versions),
    ]
