# Generated by Django 6.0.5 on 2026-07-09 00:25
#
# P1: give HabitLog / Schedule / ScheduleDay a nullable `version` FK and backfill
# it from `tier`. Additive — `tier` stays populated as the live source and the
# cross-check; nothing reads `version` yet (that's P2). The backfill is the part
# that must not be skipped: without it every past log/placement would read as
# untiered once P2 flips to versions.

import django.db.models.deletion
from django.db import migrations, models


def backfill_version_from_tier(apps, schema_editor):
    """Point every tiered row at the matching rung. We map by LABEL, not level:
    a Version's `level` was renumbered per-habit in P0, but its `label` is exactly
    the Tier the row was copied from, and a tag is unique per habit — so
    (habit, tier) -> the one Version with that label. Rows with tier=null stay
    version=null (whole-habit rows keep their meaning)."""
    Version = apps.get_model("habits", "Version")

    vmap = {}   # (habit_id, tier_id) -> version_id
    for v in Version.objects.exclude(label_id=None).values("id", "habit_id", "label_id"):
        vmap[(v["habit_id"], v["label_id"])] = v["id"]

    for model_name in ("HabitLog", "Schedule", "ScheduleDay"):
        Model = apps.get_model("habits", model_name)
        to_update = []
        for row in Model.objects.exclude(tier_id=None).only(
            "id", "habit_id", "tier_id", "version_id"
        ):
            vid = vmap.get((row.habit_id, row.tier_id))
            if vid is not None and row.version_id != vid:
                row.version_id = vid
                to_update.append(row)
        if to_update:
            Model.objects.bulk_update(to_update, ["version_id"], batch_size=500)


def clear_version(apps, schema_editor):
    for model_name in ("HabitLog", "Schedule", "ScheduleDay"):
        apps.get_model("habits", model_name).objects.update(version_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0036_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='habits.version'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='habits.version'),
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='habits.version'),
        ),
        # Fill the new columns from `tier`. NO version-keyed constraints here —
        # they're deferred to P2/P3 (a version-null unique would collide with the
        # tier-only writers still live during coexistence).
        migrations.RunPython(backfill_version_from_tier, clear_version),
    ]
