# Generated by Django 6.0.5 on 2026-07-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0037_habitlog_version_schedule_version_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habitlog',
            name='one_log_per_habit_date_tier',
        ),
        migrations.RemoveConstraint(
            model_name='habitlog',
            name='one_untiered_log_per_habit_date',
        ),
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(condition=models.Q(('version__isnull', False)), fields=('habit', 'date', 'version'), name='one_log_per_habit_date_version'),
        ),
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(condition=models.Q(('version__isnull', True)), fields=('habit', 'date'), name='one_untiered_log_per_habit_date_v'),
        ),
    ]
