# Generated by Django 6.0.5 on 2026-07-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0038_remove_habitlog_one_log_per_habit_date_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspiration',
            name='color',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
