# Generated by Django 6.0.5 on 2026-07-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0039_aspiration_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspiration',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
