# Generated by Django 6.0.5 on 2026-08-06 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0040_aspiration_target_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=1)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='habits.habit')),
            ],
            options={
                'ordering': ['habit_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VersionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_steps', to='habits.step')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_steps', to='habits.version')),
            ],
            options={
                'ordering': ['version_id', 'step__order'],
            },
        ),
        migrations.CreateModel(
            name='StepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('done', models.BooleanField(default=True)),
                ('version_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.versionstep')),
            ],
        ),
        migrations.AddConstraint(
            model_name='versionstep',
            constraint=models.UniqueConstraint(fields=('version', 'step'), name='one_amount_per_version_step'),
        ),
        migrations.AddConstraint(
            model_name='steplog',
            constraint=models.UniqueConstraint(fields=('version_step', 'date'), name='one_step_log_per_day'),
        ),
    ]
