# Generated by Django 6.0.5 on 2026-08-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0041_step_versionstep_steplog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='target_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
