# Generated by Django 6.0.5 on 2026-08-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0044_version_duration_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='kind',
            field=models.CharField(choices=[('HABIT', 'Habit'), ('TASK', 'Task')], default='HABIT', max_length=10),
        ),
    ]
